apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
spec:
  replicas: 3
  selector:
    matchLabels:
      run: juiceshop
  template:
    metadata:
      labels:
        run: juiceshop
    spec:
      containers:
      - name: juiceshop
        image: devopseasy/juiceshop:1.0.0-5
        ports:
          - containerPort: 3000
        imagePullPolicy: IfNotPresent
