apiVersion: v1
kind: Service
metadata:
  name: juiceshop
  labels:
    run: juiceshop
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    run: juiceshop
